name: Build and publish

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Cache Bun dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .bun
            bun.lock
            node_modules
          key: bun-deps-${{ hashFiles('bun.lock') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun ci
      - run: bun run build
      - uses: actions/upload-artifact@v4
        with:
          name: argus
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: argus
          path: dist/
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --dry-run
      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Rename build artifact
        run: |
          mv dist/* dist/argus-$VERSION
      - name: Upload versioned artifact
        uses: actions/upload-artifact@v4
        with:
          name: argus
          path: dist/
