name: Lint, type-check and format

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    name: Setup Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Cache Bun dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .bun
            bun.lock
            node_modules
          key: bun-deps-${{ hashFiles('bun.lock') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun ci

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Restore Bun cache
        uses: actions/cache@v3
        with:
          path: |
            .bun
            bun.lockb
            node_modules
          key: bun-deps-${{ hashFiles('bun.lock') }}
      - run: bun run lint:check

  type-check:
    name: Type-Check
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Restore Bun cache
        uses: actions/cache@v3
        with:
          path: |
            .bun
            bun.lockb
            node_modules
          key: bun-deps-${{ hashFiles('bun.lock') }}
      - run: bun run type-check

  format:
    name: Format
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Restore Bun cache
        uses: actions/cache@v3
        with:
          path: |
            .bun
            bun.lockb
            node_modules
          key: bun-deps-${{ hashFiles('bun.lock') }}
      - run: bun run fmt:check
